var valores = [true, 5, false, "hola", "adios", 2];
alert("¿Es \"hola\" mayor que \"adios\"?");
alert(valores[3]>valores[4]);
alert("¿Es \"hola\" menor que \"adios\"?");
alert(valores[3]<valores[4]);
alert("True es distinto de False");
alert(valores[0]!=valores[2]);
alert("True es igual a False");
alert(valores[0]==valores[2]);
alert("5 + 2");
alert(valores[1]+valores[5]);
alert("5 - 2");
alert(valores[1]-valores[5]);
alert("5 * 2");
alert(valores[1]*valores[5]);
alert("5 / 2");
alert(valores[1]/valores[5]);
alert("5 % 2");
alert(valores[1]%valores[5]);
